package MathGenerator;
//import javax.swing.JOptionPane;

//This class contains two boolean arrays for the a victory and lose screens, along with getter methods for both of them.
public class Ricos {


	//all answer choices for words:
	

	private boolean[][] HappyRico = new boolean[][] { 
		{false, false, false,
			false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false,  true, false, false}, 
		{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false, false, false,  true, false}, 
		{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,  true, false,  true, false,  true, false,  true,  true,  true, false,  true, false,  true, false,  true},
		{false, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false,  true, false,  true, false,  true, false,  true, false,  true, false,  true, false,  true, false,  true},
		{false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false,  true, false,  true, false,  true, false,  true,  true,  true, false,  true, false,  true, false,  true},
		{false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true, false, false,  true, false, false,  true, false,  true, false, false,  true, false, false,  true},
		{false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true, false,  true, false, false,  true, false,  true, false, false,  true, false, false,  true},
		{false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true, false, false,  true, false,  true, false, false,  true, false,  true, false}, 
		{false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true, false, false, false, false, false, false, false, false, false,  true, false, false}, 
		{false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true,  true,  true,  true,  true,  true, false,  true, false, false, false, false, false,  true,  true,  true, false, false, false}, 
		{false, false, false, false, false, false, false, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true, false, false,  true, false, false, false,  true, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true, false, false,  true, false, false, false,  true, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true, false,  true, false, false, false,  true, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false,  true,  true, false, false, false, false, false, false, false, false,  true,  true,  true,  true, false,  true,  true, false,  true, false,  false,  true, true, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false,  true,  true, false,  true,  true,  true, false, false, false, false, false,  true, false, false, false,  true,  true, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false,  true, false, false,  true, false, false, false, false, false, false, false, false, false, false,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false,  true,  true,  true,  true,  true,  true, false,  true,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false, false,  true,  true, false,  true,  true,  true, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false,  true,  true,  true,  true, false, false, false, false, false, false, false, false}, 
		{false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false}, 
		{false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false}, 
		{false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false}, 
		{false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true,  true,  true,  true,  true, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
		{false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
		{false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
		{false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
		{false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
		{false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
		{false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
		{false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
		{false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
		{false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
		{false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
		};
	
	
		private boolean[][] SadRico = new boolean[][] { 
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false,  true, false, false}, 
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false, false, false,  true, false}, 
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,  true, false,  true,  true,  true, false,  true,  true,  true, false,  true,  true,  true, false,  true},
			{false, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false,  true, false,  true, false,  true, false,  true, false,  true, false,  true, false,  true, false,  true},
			{false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false,  true, false,  true, false,  true, false,  true, false,  true, false,  true, false,  true, false,  true},
			{false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true, false,  true,  true, false, false,  true, false,  true, false,  true, false,  true, false,  true},
			{false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true,  true, false,  true, false,  true, false,  true, false,  true, false,  true, false,  true},
			{false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true,  true,  true, false,  true,  true,  true, false,  true}, 
			{false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true, false, false, false, false, false, false, false, false, false, false,  true, false}, 
			{false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true,  true,  true,  true,  true,  true, false,  true, false, false, false, false, false,  true,  true,  true,  true, false, false}, 
			{false, false, false, false, false, false, false, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true, false, false,  true, false, false, false,  true, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true, false, false,  true, false, false, false,  true, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false,  true, false,  true,  true,  true,  true, false,  true, false, false, false,  true, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false,  true,  true, false,  true, false, false, false, false, false, false, false,  true, false, false, false,  true,  true, false,  true, false,  false,  true, true, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false,  true,  true, false, false,  true, false, false, false, false, false,  true,  true, false, false, false,  true,  true, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false,  true, false, false,  true,  true, false, false, false, false, false, false, false, false, false,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false, false,  true, false, false, false, false,  true,  true,  true,  true,  true,  true, false,  true,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false, false,  true,  true, false,  true,  true,  true, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false,  true,  true,  true,  true, false, false, false, false, false, false, false, false}, 
			{false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false}, 
			{false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false}, 
			{false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false}, 
			{false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true,  true,  true,  true,  true, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
			{false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
			{false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
			{false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
			{false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
			{false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
			{false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
			{false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
			{false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
			{false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
			{false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true, false, false,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true}, 
			};
		
	
	
	
	
	Ricos() {}
	
	public boolean[][] getHappyRico(){
		return HappyRico;
	}
	
	
	public boolean[][] getSadRico(){
		return SadRico;
	}
	
	
}